#!/bin/bash
# Note: Don't forget to clear the ~/.vim/aliases file before running so you
# don't get outdated binds.

grep "vim\ " ~/.bash_aliases \
	| sed \
		-e 's/alias\ /map <leader>/g' \
		-e 's/=/\ :e/g' \
		-e 's/\"vim//g' \
		-e 's/\"/<CR>/g' > ~/.vim/aliases

grep "cd\ " ~/.bash_aliases \
	| sed \
		-e 's/alias\ /map <leader>/g' \
		-e 's/=/\ :e\ /g' -e 's/\"cd\ //g' \
		-e 's/\"/<CR>/g' >> ~/.vim/aliases

if [[ $(grep "source ~/.vim/aliases" ~/.vimrc) ]]; then
	printf "Source line exists.\n"
else
	{
	printf "\n\" This file was generated by $(basename $0)\n"
	printf "source ~/.vim/aliases\n"
	} >> ~/.vimrc

	printf "Placed source line in ~/.vimrc.\n"
fi
